import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.scss";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="main-theme">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
