const VISISOLAR_DATA = [
  {
    name: "JS 131 S (Cocok untuk 2-4 orang)",
    diameterTangki: "110x47x47 (cm)",
    materialTangki: "Stainless Steel 316 L (cm)",
    dimensiPanel: "180x100x80",
    materialBoxPanel: "Galvalum",
    tebalTangkiDalam: "3mm",
    beratKosongTangki: "48 Kg",
    beratIsiTangki: "148kg",
    jumlahPanel: "1 Panel",
    beratKosongPanel: "42kg",
    beratIsiPanel: "45Kg",
    backupElectricHeater: "500 Watt",
    jumlahAlurPipaRiser: "8 Alur",
    insulationTangki: "High Density Polyethane 7cm",
    coverPanelKolekter: "Ice Tempered Glass",
    materialAbsorber: "Tembaga (CU) Dm5.8 (Header) 3.8 (Riser)",
    aksesoris: "ELCB, Safety Valve, Check Valve",
  },
  {
    name: "JS 151 S (Cocok untuk 4-5 orang)",
    diameterTangki: "120x47x47 (cm)",
    materialTangki: "Stainless Steel 316 L (cm)",
    dimensiPanel: "180x100x80",
    materialBoxPanel: "Galvalum",
    tebalTangkiDalam: "3mm",
    beratKosongTangki: "56 Kg",
    jumlahPanel: "1 Panel",
    beratKosongPanel: "42kg",
    beratIsiPanel: "45kg",
    backupElectricHeater: "800 Watt",
    jumlahAlurPipaRiser: "8 Alur",
    insulationTangki: "High Density Polyethane 7cm",
    coverPanelKolekter: "Ice Tempered Glass",
    materialAbsorber: "Tembaga (CU) Dm5.8 (Header) 3.8 (Riser)",
    aksesoris: "ELCB, Safety Valve, Check Valve",
  },
  {
    name: "JS 302 S (Cocok untuk 5-9 orang)",
    diameterTangki: "220x47x47 (cm)",
    materialTangki: "Stainless Steel 316 L (cm)",
    dimensiPanel: "180x100x80",
    materialBoxPanel: "Galvalum",
    tebalTangkiDalam: "3mm",
    beratKosongTangki: "98 Kg",
    jumlahPanel: "2 Panel",
    beratKosongPanel: "84 Kg",
    beratIsiPanel: "90 Kg",
    backupElectricHeater: "1500 Watt",
    jumlahAlurPipaRiser: "8 Alur",
    insulationTangki: "High Density Polyethane 7cm",
    coverPanelKolekter: "Ice Tempered Glass",
    materialAbsorber: "Tembaga (CU) Dm5.8 (Header) 3.8 (Riser)",
    aksesoris: "ELCB, Safety Valve, Check Valve",
  },
];

export default VISISOLAR_DATA;
